<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employee extends \BackendBundle\Entity\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'dob', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'address', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'nationality', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'emergencyContactName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'emergencyContactMobile', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'bankName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'bankBsb', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'bankAccountNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'tfnNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'abnNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'superannuationName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'superannuationNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'approved', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'lattitude', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'longitude', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'positions', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'positionName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'user', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'employeeCategory', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'employeeOrderCategory', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'userDeclearation', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'slNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'archived'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'dob', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'address', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'nationality', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'emergencyContactName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'emergencyContactMobile', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'bankName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'bankBsb', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'bankAccountNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'tfnNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'abnNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'superannuationName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'superannuationNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'approved', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'lattitude', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'longitude', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'positions', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'positionName', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'user', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'employeeCategory', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'employeeOrderCategory', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'userDeclearation', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'slNo', '' . "\0" . 'BackendBundle\\Entity\\Employee' . "\0" . 'archived'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isArchived()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isArchived', []);

        return parent::isArchived();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchived(bool $archived)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchived', [$archived]);

        return parent::setArchived($archived);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDob($dob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDob', [$dob]);

        return parent::setDob($dob);
    }

    /**
     * {@inheritDoc}
     */
    public function getDob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDob', []);

        return parent::getDob();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality($nationality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmergencyContactName($emergencyContactName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmergencyContactName', [$emergencyContactName]);

        return parent::setEmergencyContactName($emergencyContactName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmergencyContactName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmergencyContactName', []);

        return parent::getEmergencyContactName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmergencyContactMobile($emergencyContactMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmergencyContactMobile', [$emergencyContactMobile]);

        return parent::setEmergencyContactMobile($emergencyContactMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmergencyContactMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmergencyContactMobile', []);

        return parent::getEmergencyContactMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankName($bankName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankName', [$bankName]);

        return parent::setBankName($bankName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankName', []);

        return parent::getBankName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankBsb($bankBsb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankBsb', [$bankBsb]);

        return parent::setBankBsb($bankBsb);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankBsb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankBsb', []);

        return parent::getBankBsb();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankAccountNo($bankAccountNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankAccountNo', [$bankAccountNo]);

        return parent::setBankAccountNo($bankAccountNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccountNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccountNo', []);

        return parent::getBankAccountNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTfnNo($tfnNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTfnNo', [$tfnNo]);

        return parent::setTfnNo($tfnNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTfnNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTfnNo', []);

        return parent::getTfnNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbnNo($abnNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbnNo', [$abnNo]);

        return parent::setAbnNo($abnNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbnNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbnNo', []);

        return parent::getAbnNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperannuationName($superannuationName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperannuationName', [$superannuationName]);

        return parent::setSuperannuationName($superannuationName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperannuationName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperannuationName', []);

        return parent::getSuperannuationName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperannuationNo($superannuationNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperannuationNo', [$superannuationNo]);

        return parent::setSuperannuationNo($superannuationNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperannuationNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperannuationNo', []);

        return parent::getSuperannuationNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setApproved($approved)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApproved', [$approved]);

        return parent::setApproved($approved);
    }

    /**
     * {@inheritDoc}
     */
    public function getApproved()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApproved', []);

        return parent::getApproved();
    }

    /**
     * {@inheritDoc}
     */
    public function getLattitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLattitude', []);

        return parent::getLattitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLattitude(float $lattitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLattitude', [$lattitude]);

        return parent::setLattitude($lattitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude(float $longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\BackendBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeCategory(\BackendBundle\Entity\EmployeeCategory $employeeCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeCategory', [$employeeCategory]);

        return parent::setEmployeeCategory($employeeCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeCategory', []);

        return parent::getEmployeeCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeOrderCategory(\BackendBundle\Entity\EmployeeOrderCategory $employeeOrderCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeOrderCategory', [$employeeOrderCategory]);

        return parent::setEmployeeOrderCategory($employeeOrderCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeOrderCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeOrderCategory', []);

        return parent::getEmployeeOrderCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserDeclearation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserDeclearation', []);

        return parent::getUserDeclearation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserDeclearation(\BackendBundle\Entity\UserDeclearation $userDeclearation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserDeclearation', [$userDeclearation]);

        return parent::setUserDeclearation($userDeclearation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlNo', []);

        return parent::getSlNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlNo($slNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlNo', [$slNo]);

        return parent::setSlNo($slNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositions', []);

        return parent::getPositions();
    }

    /**
     * {@inheritDoc}
     */
    public function setPositions(string $positions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPositions', [$positions]);

        return parent::setPositions($positions);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositionName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositionName', []);

        return parent::getPositionName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPositionName(string $positionName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPositionName', [$positionName]);

        return parent::setPositionName($positionName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeName', []);

        return parent::getEmployeeName();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncryptedId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncryptedId', []);

        return parent::getEncryptedId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncryptedId(string $encryptedId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncryptedId', [$encryptedId]);

        return parent::setEncryptedId($encryptedId);
    }

    /**
     * {@inheritDoc}
     */
    public function encodeId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encodeId', [$id]);

        return parent::encodeId($id);
    }

}
