<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Admin extends \BackendBundle\Entity\Admin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'dob', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'abnNo', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'mobileNo', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'accountPayableEmail', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'accountPayableNo', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'creditLimit', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'invoiceDueDate', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'comments', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'extra', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'dob', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'abnNo', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'mobileNo', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'accountPayableEmail', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'accountPayableNo', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'creditLimit', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'invoiceDueDate', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'comments', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'extra', '' . "\0" . 'BackendBundle\\Entity\\Admin' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Admin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDob', []);

        return parent::getDob();
    }

    /**
     * {@inheritDoc}
     */
    public function setDob($dob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDob', [$dob]);

        return parent::setDob($dob);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbnNo($abnNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbnNo', [$abnNo]);

        return parent::setAbnNo($abnNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbnNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbnNo', []);

        return parent::getAbnNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileNo($mobileNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileNo', [$mobileNo]);

        return parent::setMobileNo($mobileNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileNo', []);

        return parent::getMobileNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountPayableEmail($accountPayableEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountPayableEmail', [$accountPayableEmail]);

        return parent::setAccountPayableEmail($accountPayableEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountPayableEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountPayableEmail', []);

        return parent::getAccountPayableEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountPayableNo($accountPayableNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountPayableNo', [$accountPayableNo]);

        return parent::setAccountPayableNo($accountPayableNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountPayableNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountPayableNo', []);

        return parent::getAccountPayableNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditLimit($creditLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditLimit', [$creditLimit]);

        return parent::setCreditLimit($creditLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditLimit', []);

        return parent::getCreditLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceDueDate($invoiceDueDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceDueDate', [$invoiceDueDate]);

        return parent::setInvoiceDueDate($invoiceDueDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceDueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceDueDate', []);

        return parent::getInvoiceDueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', [$comments]);

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtra($extra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtra', [$extra]);

        return parent::setExtra($extra);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtra', []);

        return parent::getExtra();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\BackendBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncryptedId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncryptedId', []);

        return parent::getEncryptedId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncryptedId(string $encryptedId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncryptedId', [$encryptedId]);

        return parent::setEncryptedId($encryptedId);
    }

    /**
     * {@inheritDoc}
     */
    public function encodeId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encodeId', [$id]);

        return parent::encodeId($id);
    }

}
