<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EmployeeSkillCompetencyDocument extends \BackendBundle\Entity\EmployeeSkillCompetencyDocument implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'issueDate', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'expiryDate', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'description', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'employee', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'skillCompetencyList', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'documents'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'issueDate', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'expiryDate', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'description', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'employee', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'skillCompetencyList', '' . "\0" . 'BackendBundle\\Entity\\EmployeeSkillCompetencyDocument' . "\0" . 'documents'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EmployeeSkillCompetencyDocument $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssueDate($issueDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssueDate', [$issueDate]);

        return parent::setIssueDate($issueDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssueDate', []);

        return parent::getIssueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiryDate($expiryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiryDate', [$expiryDate]);

        return parent::setExpiryDate($expiryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiryDate', []);

        return parent::getExpiryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployee(\BackendBundle\Entity\Employee $employee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployee', [$employee]);

        return parent::setEmployee($employee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployee', []);

        return parent::getEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkillCompetencyList(\BackendBundle\Entity\SkillCompetencyList $skillCompetencyList = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkillCompetencyList', [$skillCompetencyList]);

        return parent::setSkillCompetencyList($skillCompetencyList);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkillCompetencyList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkillCompetencyList', []);

        return parent::getSkillCompetencyList();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncryptedId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncryptedId', []);

        return parent::getEncryptedId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncryptedId(string $encryptedId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncryptedId', [$encryptedId]);

        return parent::setEncryptedId($encryptedId);
    }

    /**
     * {@inheritDoc}
     */
    public function encodeId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encodeId', [$id]);

        return parent::encodeId($id);
    }

}
