<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpk5ptn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpk5ptn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXpk5ptn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXpk5ptn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXpk5ptn\appProdProjectContainer(array(
    'container.build_hash' => 'Xpk5ptn',
    'container.build_id' => '1b6408bd',
    'container.build_time' => 1539230477,
));
