BackendBundle\Entity\EmployeeWhiteCard:
    type: entity
    table: employee_white_card
    indexes:
        fk_employee_white_card_employee_other_document1_idx:
            columns:
                - employee_other_document_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        employeeOtherDocument:
            targetEntity: EmployeeOtherDocument
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                employee_other_document_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
