<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\Core\AController' shared autowired service.

return $this->services['AppBundle\Controller\Core\AController'] = new \AppBundle\Controller\Core\AController();
