<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.default_connection' shared service.

$a = ${($_ = isset($this->services['vich_uploader.metadata_reader']) ? $this->services['vich_uploader.metadata_reader'] : $this->getVichUploader_MetadataReaderService()) && false ?: '_'};
$b = ${($_ = isset($this->services['vich_uploader.upload_handler']) ? $this->services['vich_uploader.upload_handler'] : $this->load(__DIR__.'/getVichUploader_UploadHandlerService.php')) && false ?: '_'};

$c = new \Vich\UploaderBundle\Adapter\ORM\DoctrineORMAdapter();

$d = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this);
$d->addEventSubscriber(new \Vich\UploaderBundle\EventListener\Doctrine\CleanListener('document', $c, $a, $b));
$d->addEventSubscriber(new \Vich\UploaderBundle\EventListener\Doctrine\UploadListener('document', $c, $a, $b));
$d->addEventSubscriber(new \Vich\UploaderBundle\EventListener\Doctrine\RemoveListener('document', $c, $a, $b));
$d->addEventListener(array(0 => 'loadClassMetadata'), ${($_ = isset($this->services['doctrine.orm.default_listeners.attach_entity_listeners']) ? $this->services['doctrine.orm.default_listeners.attach_entity_listeners'] : $this->services['doctrine.orm.default_listeners.attach_entity_listeners'] = new \Doctrine\ORM\Tools\AttachEntityListenersListener()) && false ?: '_'});

return $this->services['doctrine.dbal.default_connection'] = ${($_ = isset($this->services['doctrine.dbal.connection_factory']) ? $this->services['doctrine.dbal.connection_factory'] : $this->services['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array())) && false ?: '_'}->createConnection(array('driver' => 'pdo_mysql', 'host' => '127.0.0.1', 'port' => 3306, 'dbname' => 'httppwfh_pwfhirecrm', 'user' => 'httppwfh_admin', 'password' => 'Toolmateshire831', 'charset' => 'UTF8', 'driverOptions' => array(), 'defaultTableOptions' => array()), new \Doctrine\DBAL\Configuration(), $d, array());
