<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\Staff\EmployeeOrderCategroyController' shared autowired service.

return $this->services['AppBundle\Controller\Staff\EmployeeOrderCategroyController'] = new \AppBundle\Controller\Staff\EmployeeOrderCategroyController();
