<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\Admin\ManageOrderController' shared autowired service.

return $this->services['AppBundle\Controller\Admin\ManageOrderController'] = new \AppBundle\Controller\Admin\ManageOrderController();
